-- DROP DATABASE CONCESIONARIO;
-- CREATE DATABASE CONCESIONARIO;
USE CONCESIONARIO;

-- CREATE TABLE USUARIO(
-- NOM VARCHAR (50),
-- CONTRASENIA VARCHAR (50));

-- CREATE TABLE PROPIETARIO(
-- ID INT PRIMARY KEY,
-- NOM_P VARCHAR(50),
-- FECHA_NAC DATE);

-- CREATE TABLE COCHE (
-- MATRICULA CHAR (7), 
-- MARCA VARCHAR (50),
-- MODELO VARCHAR (50),
-- EDAD INT,
-- PRECIO FLOAT,
-- ID INT,
-- FOREIGN KEY (ID) REFERENCES PROPIETARIO (ID) ON DELETE CASCADE);

-- INSERT INTO USUARIO VALUES ('ADMIN', 'ADMIN'), ('AAAA', '1234');
SELECT *FROM USUARIO;
SELECT *FROM PROPIETARIO;
SELECT *FROM COCHE;
