/*CREATE DATABASE PEDIDOS;*/
USE PEDIDOS;

/*CREATE TABLE PEDIDO(
RefPed INT PRIMARY KEY,
FecPed DATE);

CREATE TABLE ARTICULO(
CodArt INT PRIMARY KEY,
DesArt VARCHAR (20),
PVPArt FLOAT);

CREATE TABLE LINEAPEDIDO(
RefPed INT,
CodArt INT,
CantArt INT,
FOREIGN KEY (RefPed) REFERENCES PEDIDO (RefPed),
FOREIGN KEY (CodArt) REFERENCES ARTICULO (CodArt));*/

/*CREATE USER ADMINPEDIDOS IDENTIFIED BY '1234';*/
/*GRANT ALL PRIVILEGES ON PEDIDOS.* TO ADMINPEDIDOS;*/
/*GRANT GRANT OPTION ON PEDIDOS.* TO ADMINPEDIDOS;*/

/*CREATE USER CONSULPEDIDOS IDENTIFIED BY 'ABCD';*/
/*GRANT SELECT, CREATE, DROP, UPDATE, CREATE VIEW, INDEX ON PEDIDOS.* TO CONSULPEDIDOS;*/

/*CREATE USER PROCPEDIDOS@localhost identified by '1234abcd' with max_queries_per_hour 30 max_updates_per_hour 30 max_user_connections 4;*/
/*GRANT CREATE ROUTINE, ALTER ROUTINE ON PEDIDOS.* TO PROCPEDIDOS@localhost;*/

/*CREATE USER MODIFPEDIDOS IDENTIFIED BY '123456789';*/
/*GRANT SELECT, INSERT, DELETE, CREATE, UPDATE(DesArt, PVPArt) ON PEDIDOS.ARTICULO TO MODIFPEDIDOS;*/

/*REVOKE CREATE ROUTINE, ALTER ROUTINE ON PEDIDOS.* FROM PROCPEDIDOS@localhost;*/
/*DROP USER PROCPEDIDOS@localhost;*/

/*SHOW GRANTS FOR CONSULPEDIDOS;*/
/*REVOKE CREATE, DROP, UPDATE ON PEDIDOS.* FROM CONSULPEDIDOS;*/

/*CREATE ROLE RolRRHH;*/
/*GRANT SELECT ON PEDIDOS.ARTICULO TO RolRRHH;*/
/*GRANT SELECT ON PEDIDOS.PEDIDO TO RolRRHH;*/
/*GRANT CREATE, ALTER, DROP, INSERT ON PEDIDOS.* TO RolRRHH;*/
/*GRANT CREATE, ALTER, DROP, INSERT, UPDATE(RefPed, FecPed) ON PEDIDOS.PEDIDO TO RolRRHH;*/

/*CREATE USER rrhh1 IDENTIFIED BY 'ABCDEF' default role RolRRHH password expire interval 30 day;
CREATE USER rrhh2 IDENTIFIED BY 'ABCDEF' default role RolRRHH password expire interval 30 day;
CREATE USER rrhh3 IDENTIFIED BY 'ABCDEF' default role RolRRHH password expire interval 30 day;*/



