/*CREATE DATABASE EJEMPLO;*/
USE EJEMPLO;
/*CREATE TABLE DEPARTAMENTO(
ID INT PRIMARY KEY,
NOMD VARCHAR (50));

CREATE TABLE PROFESOR(
DNI CHAR (9) PRIMARY KEY,
NOM VARCHAR(50),
EDAD INT CHECK(EDAD > 0),
ASIGNATURA ENUM('PGR', 'BD'),
ID INT,
FOREIGN KEY (ID) REFERENCES DEPARTAMENTO (ID));

INSERT INTO DEPARTAMENTO VALUES(1, 'INFORMATICA'),(2, 'INTEGRACION SOCIAL'),(3, 'IMAGEN Y SONIDO'),(4, 'SANIDAD'),(5, 'FOL');

INSERT INTO PROFESOR VALUES ('11111111A', 'JOSE', 40, 'BD', 1),
							('22222222A', 'ANTONIO', 60, 'PGR', 1),
                            ('33333333A', 'ALBERTO', 30, 'PGR', 3),
                            ('44444444A', 'RAMONA', 50, 'PGR', 3),
                            ('55555555A', 'LAURA', 23, 'BD', 4),
                            ('66666666A', 'JUAN', 37, 'PGR', 4),
                            ('77777777A', 'JUANA', 53, 'PGR', 2);*/

/*INSERT INTO PROFESOR VALUES('88888888A', 'AMAIA', 17, 'BD', 1);*/

/*DELIMITER //
CREATE PROCEDURE DeptProc(NomDpto VARCHAR(50))
BEGIN
DECLARE Cant INT;
SELECT COUNT(*) INTO Cant FROM PROFESOR WHERE ID IN (SELECT ID FROM DEPARTAMENTO WHERE NOMD=NomDpto);
END //
DELIMITER ; */
/*CALL DeptProc('INFORMATICA'); */                          

/*DELIMITER //
CREATE PROCEDURE MayorEdad (DniProf CHAR(9))
BEGIN
	DECLARE E INT;
	SELECT EDAD INTO E FROM PROFESOR WHERE DNI = DniProf;
	IF E>18 THEN
		SELECT CONCAT('LA PERSONA CON DNI', DniProf, "ES MAYOR DE EDAD");
	ELSE 
		SELECT CONCAT('LA PERSONA CON DNI', DniProf, 'ES MENOR DE EDAD');
	END IF;
END; */

/*CALL MayorEdad('11111111A');*/
/*DROP PROCEDURE SumarEdad;
DELIMITER //
CREATE PROCEDURE SumarEdad (NomDpto VARCHAR(20))
BEGIN  
	DECLARE CONTADOR INT;
    SELECT COUNT(*) INTO CONTADOR FROM PROFESOR WHERE ID IN (SELECT ID FROM DEPARTAMENTO WHERE NOMD=NomDpto);
    WHILE NOT(MAX(CONTADOR)) DO
    IF NOMD = NomDpto THEN
		UPDATE EDAD SET EDAD= EDAD+1 WHERE ID = (SELECT ID FROM DEPARTAMENTO WHERE NOMD = NomDpto);
	ELSE 
		SELECT CONCAT('NO SE PUEDE ACTUALIZAR');
	END IF;
		SELECT CONCAT('EL PROFESOR', NOM, "TIENE", EDAD, 'AÑOS');
    END WHILE;
END;*/

/*CALL SumarEdad('INFORMATICA');*/

/*DELIMITER //
CREATE FUNCTION ObtenerEdad(DniProf CHAR(9)) RETURNS INT
READS SQL DATA
BEGIN
	DECLARE E INT;
	SELECT EDAD INTO E FROM PROFESOR WHERE DNI = DniProf;
    RETURN E;
END;*/

/*DELIMITER //
CREATE PROCEDURE InsertarProfesor(DNI CHAR(9), NOMBRE VARCHAR(50), EDAD INT, ASIGNATURA ENUM("PGR", "BD"), NOMDPTO VARCHAR(50))
BEGIN 
	DECLARE N INT;
		SELECT ID INTO N FROM DEPARTAMENTO WHERE NOMD = NOMDPTO;
    IF (EDAD>18) THEN 
		INSERT INTO PROFESOR VALUES (DNI, NOMBRE, EDAD, ASIGNATURA, N);
        SELECT CONCAT('EL PROFESOR ', NOMBRE, ' CON DNI ', DNI, ' Y UNA EDAD DE ', EDAD, ' AÑOS ', 
						' ENSEÑA ', ASIGNATURA, ' Y PERTENECE A UN DEPARTAMENTO CUYO ID ES ', N);
    ELSE 
		SELECT CONCAT("NO SE PUEDE INTRODUCIR PROFESOR AL SER MENOR DE EDAD");
    END IF;
END ;*/

/*CALL InsertarProfesor('60101010A', 'BBBBB', 40, 'BD', 'FOL');*/
/*SELECT *FROM PROFESOR;*/

/*DELIMITER //
CREATE PROCEDURE BorrarDepartamento(NomP VARCHAR(50))
BEGIN
	DECLARE I INT;
    SELECT COUNT(ID) INTO I FROM PROFESOR WHERE ID = (SELECT ID FROM PROFESOR WHERE NomP = NOM);
    IF (I>2) THEN 
		DELETE PROFESOR FROM PROFESOR WHERE NomP = NOM;
    ELSE
		SELECT CONCAT('NO SE PUEDE BORRAR AL NO HABER MAS DE 2 PROFESORES EN EL DEPARTAMENTO');
    END IF;
END ;*/

CALL BorrarDepartamento ('ANTONIO');
SELECT *FROM PROFESOR;
    
