/* (Creacion de la base de datos con las tablas.)
CREATE DATABASE HOSPITALCRUCES
USE HOSPITALCRUCES;

CREATE TABLE CIUDAD (
COD_C INT PRIMARY KEY,
NOM_C VARCHAR(20));

CREATE TABLE HOSPITAL(
COD_H INT,
NOM_H VARCHAR(20),
COD_C INT, 
PRIMARY KEY (COD_H, NOM_H),
FOREIGN KEY (COD_C) REFERENCES CIUDAD (COD_C));

CREATE TABLA ESPECIALIDAD(
COD_ESP INT PRIMARY KEY;
NOM_ESP VARCHAR(20));

CREATE TABLE MEDICO(
DNI_M INT PRIMARY KEY,
NOM_M VARCHAR(20),
EDAD INT,
SALARIO INT,
COD_ESP INT,
COD_H INT,
FOREIGN KEY (COD_ESP) REFERENCES ESPECIALIDAD (COD_ESP),
FOREIGN KEY (COD_H) REFERENCES HOSPITAL (COD_H));*/

/* (Insertar los datos)
INSERT INTO VALUES("01", "BILBAO"), ("02", "LEIOA"), ("03", "ERANDIO"), ("04", "BASAURI"), ("05"," BARAKALDO");
INSERT INTO VALUES("01", "CRUCES", "05"), ("02", "BASAURI", "04"), ("03", "BASURTO", "01"), ("04", "VIRGEN BLANCA", "01"), ("05", "DOCTOR SAN SEBASTIAN", "01"), ("06", "QUIRON", "02");
INSERT INTO VALUES("01", "PEDIATRIA"), ("02", "PSICOLOGIA"), ("03", "NEUROLOGIA"), ("04", "GINECOLOGIA");
INSERT INTO VALUES("111", "GONZALEZ", "35", "3000", "01", "06"), ("222", "PEREZ", "45", "3500", "01", "06"), ("333", "MARTINEZ, "25", "1000", "04", "01"), ("444", "GOMEZ", "30", "2500", "04", "01"), ("555", "PEREZ", "55", "3000", "01", "03"), ("666", "LLONA", "56", "3000", "02", "05"), ("777", "MARCOS", "60", "4000", "03", "05");
*/

/* (Ver las tablas)
SELECT* FROM CIUDAD;
SELECT* FROM MEDICO;
SELECT * FROM HOSPITAL;
SELECT NOM_ESP FROM ESPECIALIDAD WHERE COD_ESP = 2;
SELECT DNI_M FROM MEDICO WHERE EDAD > 40;
SELECT NOM_M FROM MEDICO WHERE (EDAD > 25) OR (EDAD < 25); o sino SELECT NOM_M FROM MEDICO WHERE EDAD <> 25;
SELECT NOM_M FROM MEDICO WHERE SALARIO > 3000;
SELECT NOM_H FROM HOSPITAL WHERE (COD_C = 01) OR (COD_C =02), SELECT NOM_H FROM HOSPITAL WHERE COD_C IN (01, 02);
SELECT NOM_M FROM MEDICO WHERE COD_ESP = 01;
SELECT NOM_M FROM MEDICO WHERE SUELDO BETWEEN (2000 AND 3200);
SELECT NOM_C FROM CIUDAD WHERE NOM_C LIKE "%B%";
SELECT DNI_M, NOM_M, SALARIO FROM MEDICO WHERE NOM_C = 04;
SELECT DNI_M FROM MEDICO WHERE COD_ESP = 02 OR COS_ESP = 04; o sino SELECT DNI_M FROM MEDICO WHERE COS_ESP IN (02, 04);
SELECT NOM_M FROM MEDICO WHERE COD_ESP = 01 AND NOM_H = 06;
SELECT* FROM HOSPITAL WHERE NOM_H LIKE "%O%"*/