/*CREATE DATABASE ZARA;*/
USE ZARA;

/*CREATE TABLE PRODUCTO(
ID INT PRIMARY KEY,
NOM VARCHAR (20),
PRECIO FLOAT);

CREATE TABLE CIUDAD(
ID_Ci INT PRIMARY KEY,
NOM_Ci VARCHAR(20));

CREATE TABLE TIENDA(
COD_T INT PRIMARY KEY,
NOM_T VARCHAR(20),
ID_Ci INT,
FOREIGN KEY (ID_Ci) REFERENCES CIUDAD (ID_Ci));

CREATE TABLE TRABAJADOR(
DNI CHAR(9) PRIMARY KEY,
NOMBRE VARCHAR(20),
EDAD INT);

CREATE TABLE TRABAJA(
DNI CHAR(9),
COD_T INT,
SALARIO FLOAT,
CARGO VARCHAR(20),
PRIMARY KEY (DNI, COD_T),
FOREIGN KEY (DNI) REFERENCES TRABAJADOR (DNI),
FOREIGN KEY (COD_T) REFERENCES TIENDA (COD_T));

CREATE TABLE VENDE(
ID INT,
COD_T INT,
PRIMARY KEY (ID, COD_T),
FOREIGN KEY (ID) REFERENCES PRODUCTO (ID),
FOREIGN KEY (COD_T) REFERENCES TIENDA (COD_T));*/

/*INSERT INTO PRODUCTO VALUES (01, "JEANS", 19.99), (02, "CAMISETA", 9.99);
INSERT INTO CIUDAD VALUES (1, "BILBAO"),(2, "BARAKALDO");
INSERT INTO TIENDA VALUES (111, "ZARA", 1),(222, "PULL AND BEAR", 2);
INSERT INTO TRABAJADOR VALUES ('11111111A', "ABC", 20),('22222222B', "DEF", 30);
INSERT INTO TRABAJA VALUES ('11111111A', 111, 2000.63, "ENCARGADO"),('22222222B', 222, 1080.63, "ALMACEN");
INSERT INTO VENDE VALUES (01, 111),(02, 222);*/

/*Obten el salario total de cada trabajador en todas las tiendas*/
SELECT SUM(SALARIO) FROM TRABAJA GROUP BY DNI;
