DROP DATABASE LIGAESCOLAR;
CREATE DATABASE LIGAESCOLAR;
USE LIGAESCOLAR;
CREATE TABLE EQUIPO(
IDEQUIPO INT AUTO_INCREMENT PRIMARY KEY,
NOMEQUIPO VARCHAR (20) NOT NULL UNIQUE,
ESTADIO VARCHAR(20) NOT NULL,
AFORO INT CHECK (AFORO>100) DEFAULT(1000),
ANIOFUNDACION INT CHECK (ANIOFUNDACION BETWEEN 1850 AND 2050),
CIUDAD VARCHAR(50) NOT NULL);

CREATE TABLE JUGADOR(
IDJUGADOR INT AUTO_INCREMENT PRIMARY KEY,
NOMJUGADOR VARCHAR(30) NOT NULL UNIQUE,
FECHANACIMIENTO DATE NOT NULL,
IDEQUIPO INT,
FOREIGN KEY (IDEQUIPO) REFERENCES EQUIPO (IDEQUIPO));

CREATE TABLE PARTIDO(
IDEQUIPOCASA INT,
IDEQUIPOFUERA INT,
FECHAPARTIDO DATE NOT NULL,
GOLESFUERA INT CHECK (GOLESFUERA>0) NOT NULL DEFAULT (0),
GOLESCASA INT CHECK (GOLESCASA>0) NOT NULL DEFAULT (0),
OBSERVACIONES VARCHAR(1000),
PRIMARY KEY (IDEQUIPOCASA, IDEQUIPOFUERA, FECHAPARTIDO),
FOREIGN KEY (IDEQUIPOCASA) REFERENCES EQUIPO (IDEQUIPO),
FOREIGN KEY (IDEQUIPOFUERA) REFERENCES EQUIPO (IDEQUIPO));

CREATE TABLE GOL(
IDEQUIPOCASA INT,
IDEQUIPOFUERA INT,
MINUTO INT CHECK (MINUTO BETWEEN 0 AND 130),
DESCRIPCION VARCHAR(1000) NOT NULL,
IDJUGADOR INT,
PRIMARY KEY (IDEQUIPOCASA, IDEQUIPOFUERA, MINUTO),
FOREIGN KEY (IDEQUIPOCASA, IDEQUIPOFUERA) REFERENCES PARTIDO (IDEQUIPOCASA, IDEQUIPOFUERA),
FOREIGN KEY (IDJUGADOR) REFERENCES JUGADOR (IDJUGADOR));