CREATE DATABASE RECAUDACION;

USE RECAUDACION;

CREATE TABLE VEHICULO(
MATRICULA CHAR(7) PRIMARY KEY,
MARCAMODELO VARCHAR(20) NOT NULL,
IMPUESTO INT(30) NOT NULL DEFAULT 50 CHECK (IMPUESTO>=10));

CREATE TABLE GUARDIA(
CodigoG int,
CodigoGJefe int,
Nombre varchar(30));

CREATE TABLE MULTA(
NMulta INT AUTO_INCREMENT PRIMARY KEY,
CodigoG VARCHAR(20) NOT NULL,
Matricula CHAR(7) NOT NULL,
FECHA DATE,
LUGAR VARCHAR(40) NOT NULL,
DESCRIPCION VARCHAR(50) NOT NULL,
IMPORTE INT NOT NULL CHECK (IMPORTE BETWEEN 15 AND 600),
PAGADA BOOLEAN NOT NULL);



