USE RECAUDACION;

ALTER TABLE VEHICULO 
MODIFY IMPUESTO INT;

ALTER TABLE GUARDIA
ADD COMISARIA ENUM ('BILBO', 'GETXO');

ALTER TABLE MULTA
MODIFY MATRICULA INT CHECK (MATRICULA >= 0); /*No ejecuta pero la sentencia esta bien*/

ALTER TABLE MULTA 
MODIFY DESCRIPCION VARCHAR (100) NOT NULL;
