USE FABRICA;
CREATE TABLE PROVEEDOR
(CODP INT CHECK (CODP>0) PRIMARY KEY,
NOMP VARCHAR(20) NOT NULL UNIQUE,
DIRP VARCHAR(40) NOT NULL);

USE FABRICA;
CREATE TABLE MATERIAPRIMA(
CODMP INT CHECK(CODMP>0) PRIMARY KEY,
NOMMP VARCHAR(20) NOT NULL,
CODP INT,
FOREIGN KEY (CODP) REFERENCES PROVEEDOR (CODP) ON UPDATE CASCADE);

USE FABRICA;
CREATE TABLE COMPONENTE (
CODCOM CHAR(4) PRIMARY KEY,
NOMCOMP VARCHAR(20) NOT NULL,
STOCKCOMP INT NOT NULL CHECK (STOCKCOMP>=0),
StockMinComp INT NOT NULL CHECK (StockMinComp>=0) DEFAULT 5 );

USE FABRICA;
CREATE TABLE COMPOSICION(
CODCOMPSUP CHAR(4),
CODCOMPINF CHAR(4),
CANTIDAD INT DEFAULT 1 CHECK(CANTIDAD>=0),
PRIMARY KEY(CODCOMPSUP,CODCOMPINF, CANTIDAD),
FOREIGN KEY (CODCOMPSUP) REFERENCES COMPONENTE (CODCOM),
FOREIGN KEY (CODCOMPINF) REFERENCES COMPONENTE (CODCOM));

USE FABRICA;
CREATE TABLE FABRICACION(
CODMP INT,
CODCOMP CHAR(4),
PRIMARY KEY (CODMP, CODCOMP),
FOREIGN KEY (CODMP) REFERENCES MATERIAPRIMA (CODMP),
FOREIGN KEY (CODCOMP) REFERENCES COMPONENTE (CODCOM));





