USE HOSPITALCRUCES;
/*SELECT NOM_C FROM CIUDAD WHERE COD_C = (SELECT COD_C FROM HOSPITAL WHERE NOM_H = "CRUCES");
SELECT C.NOM_C FROM CIUDAD C, HOSPITAL H WHERE C.COD_C = H.COD_C AND H.NOM_H = "CRUCES";
SELECT E.NOM_ESP FROM MEDICO M, ESPECIALIDAD E WHERE M.NOM_M = GONZALEZ AND M.COD_M = E.COD_ESP;
SELECT NOM_ESP FROM ESPECIALIDAD WHERE COD_ESP = (SELECT COD_ESP FROM MEDICO WHERE NOM_M = "GONZALEZ");
SELECT NOM_M FROM MEDICO WHERE EDAD = (SELECT MIN(EDAD) FROM MEDICO);
SELECT M.NOM_M FROM MEDICO M, ESPECIALIDAD E WHERE E.COD_ESP="NEUROLOGIA" AND E.COD_ESP = M.NOM_M;
SELECT NOM_M FROM MEDICO WHERE NOM_M = (SELECT NOM_M FROM ESPECIALIDAD WHERE COD_ESP = "NEUROLOGIA");*/
/*SELECT AVG(M.SALARIO) FROM MEDICO M, ESPECIALIDAD E WHERE M.COD_ESP = "GINECOLOGIA" AND M.COD_ESP = E.COD_ESP;*/
/*SELECT AVG(SALARIO) FROM MEDICO WHERE NOM_ESP = (SELECT NOM_ESP FROM ESPECIALIDAD WHERE NOM_ESP = "GINECOLOGIA");*/
/*SELECT *FROM ESPECIALIDAD;*/
/*SELECT NOM_H FROM HOSPITAL JOIN CIUDAD ON HOSPITAL.COD_C = CIUDAD.COD_C WHERE NOM_C = "BILBAO";*/