/*CREATE DATABASE EMPRESA;*/
USE EMPRESA;

/*CREATE TABLE DEPART(
DEPT_NO INT PRIMARY KEY,
DEPT_NOM VARCHAR (20),
LOC VARCHAR(20));

CREATE TABLE EMPLE(
EMP_NOM INT PRIMARY KEY,
APELLIDO VARCHAR (20),
OFICIO VARCHAR (20),
DIR VARCHAR (20),
FECHA_ALT DATE,
SALARIO INT,
COMISION FLOAT,
DEPT_NO INT,
FOREIGN KEY (DEPT_NO) REFERENCES DEPART (DEPT_NO));*/

CREATE VIEW VISTAEMPLEDEPT AS SELECT 
    emple.apellido,
    emple.salario, TIMESTAMPDIFF(YEAR, e.fecha_alt, CURRENT_DATE) AS antigüedad,
    dept.dnombre AS departamento
FROM 
    Emple e
JOIN 
    Depart d ON e.dept_no = d.dept_no;