USE MITRABAJO;
/*SELECT * FROM DEPARTAMENTO; (mostrar toda la tabla)*/
/*SELECT DEPT_NO FROM DEPARTAMENTO; (mostrar una columna de la tabla)*/
/*SELECT DNOMBRE, DEPT_NO FROM DEPARTAMENTO; (aparece en el orden puesto)*/
/*SELECT DISTINCT (DNOMBRE) FROM DEPARTAMENTO; (que solo aparezcan los no repetidos)*/
/*SELECT * FROM DEPARTAMENTO WHERE LOC = 'BARCELONA';*/
/*SELECT * FROM DEPARTAMENTO WHERE LOC = 'BARCELONA' AND DNOMBRE = 'RRHH';*/
/*SELECT APELLIDO FROM EMPLEADO WHERE SALARIO>2000;*/
/*SELECT EMP_NO FROM EMPLEADO WHERE OFICIO = 'VENDEDOR' OR 'DIRECTOR'; (una forma)*/
/*SELECT EMP_NO FROM EMPLEADO WHERE OFICIO IN ('VENDEDOR', 'DIRECTOR'); (OTRA FORMA)*/