/*CREATE DATABASE AGENCIA;*/
USE AGENCIA;

/*CREATE TABLE INMOBILIARIA(
COD_I INT PRIMARY KEY,
NOM_I VARCHAR (20));

CREATE TABLE CIUDAD(
COD_C INT PRIMARY KEY,
NOM_C VARCHAR (20),
N_HABITANTES INT);

CREATE TABLE INMUEBLE(
COD_IN INT PRIMARY KEY,
NOM_IN VARCHAR (20),
M2 INT,
COD_C INT,
FOREIGN KEY (COD_C) REFERENCES CIUDAD (COD_C));

CREATE TABLE PERIODICO(
COD_P INT PRIMARY KEY,
NOM_P VARCHAR (20),
NUM_LECTORES INT, 
COD_C INT,
FOREIGN KEY (COD_C) REFERENCES CIUDAD (COD_C));

CREATE TABLE PUBLICAR(
COD_I INT,
COD_P INT,
COD_IN INT,
FECHA DATE,
FOREIGN KEY (COD_I) REFERENCES INMOBILIARIA (COD_I),
FOREIGN KEY (COD_P) REFERENCES PERIODICO (COD_P),
FOREIGN KEY (COD_IN) REFERENCES INMUEBLE (COD_IN));*/

INSERT INTO INMOBILIARIA VALUES ("01", "LA VENTANA"), ("02", "LA POSADA"), ("03", "ETXEA"), ("04", "PISOS");
INSERT INTO PERIODICO VALUES ("01", "EL CORREO", "5000", "11"), ("02", "DEIA", "3000", "11"), ("03", "QUE", "5000", "11"), ("04", "EL PAIS", "2000", "55"), ("05", "ABC", "3500", "55");
INSERT INTO INMUEBLE VALUES ("", "", "", ""), ("", "", "", ""), ("", "", "", ""), ("", "", "", ""), ("", "", "", "");
INSERT INTO PUBLICAR VALUES ("01", "01", "01", "12-09-90"), ("01", "02", "01", "12-09-90"), ("", "", "", ""), ("", "", "", ""), ("", "", "", ""), ("", "", "", ""), ("", "", "", ""), ("", "", "", ""), ("", "", "", ""), ("", "", "", "");
INSERT INTO CIUDAD VALUES ("11", "BILBAO"), ("22", "GETXO"), ("33", "SOPELANA"), ("44", "BERANGO"), ("55", "MADRID");