/*CREATE DATABASE PEDIDOS1;*/
USE PEDIDOS;

/*CREATE TABLE PEDIDO1(
REFPED INT, 
FECHPEDIDO DATE);

CREATE TABLE ARTICULO1(
CODART INT,
DESART VARCHAR(20),
PVPART FLOAT);

CREATE TABLE LINEAPEDIDO1(
REFPED INT,
CANTART INT,
CODART INT,
FOREIGN KEY (REFPED) REFERENCES PEDIDO1 (REFPED),
FOREIGN KEY (CODART) REFERENCES ARTICULO1 (CODART));*/

-- DELIMITER //

-- CREATE PROCEDURE EliminarPedido(p_RefPed INT)
-- BEGIN
--     DECLARE v_FecPed DATE;
--     SELECT FecPed INTO v_FecPed FROM Pedido WHERE RefPed = p_RefPed;
--     DELETE FROM LineaPedido WHERE RefPed = p_RefPed;
--     DELETE FROM Pedido WHERE RefPed = p_RefPed;
--     SELECT 'Pedido eliminado correctamente'EliminarPedido;
-- END //
-- DELIMITER ;

DELIMITER //
CREATE FUNCTION NumPedidos(p_DesArt VARCHAR(255)) RETURNS INT
READS SQL DATA
BEGIN
    DECLARE v_NumPedidos INT;
	SELECT COUNT(DISTINCT, RefPed) INTO v_NumPedidos FROM LineaPedido  WHERE CodArt = (
    SELECT CodArt FROM ARTICULO WHERE DesArt = p_DesArt);
    SELECT CONCAT("EL ARTICULO HA SIDO SOLICITADO EN UN TOTAL DE ", v_NumPedidos, " VECES") "ARTICULO";
    RETURN v_NumPedidos;
END ;
DELIMITER ;
/*CALL EliminarPedido(1);
SELECT NumPedidos('Articulo');*/

-- SELECT *FROM ARTICULO;

